myblog/blueprints/admin.py
from datetime import datetime, timedelta

from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    request,
    current_app,
)
from flask_login import login_required, current_user

from myblog.extensions import db, csrf
from myblog.forms import SettingForm, PostForm, CategoryForm, LinkForm
from myblog.models import Post, Category, Comment, Link
from myblog.utils import redirect_back

admin_bp = Blueprint("admin", __name__)


@admin_bp.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash("Setting updated.", "success")
        return redirect(url_for("blog.index"))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template("admin/settings.html", form=form)


@admin_bp.route("/post/manage")
@login_required
def manage_post():
    page = request.args.get("page", 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config.get("BLOG_MANAGE_POST_PER_PAGE", 30)
    )
    posts = pagination.items
    return render_template("admin/manage_post.html", pagination=pagination, posts=posts)


@admin_bp.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        private = form.private.data
        # category = Category.query.get(form.category.data)
        categories = [Category.query.get(i) for i in form.categories.data]
        post = Post(title=title, body=body, private=private, categories=categories)
        db.session.add(post)
        db.session.commit()
        flash("Post created.", "success")
        return redirect(url_for("blog.show_post", post_id=post.id))
    return render_template("admin/new_post.html", form=form)


@admin_bp.route("/post/<int:post_id>/edit", methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.private = form.private.data
        # post.category = Category.query.get(form.category.data)
        categories = [Category.query.get(i) for i in form.categories.data]
        post.categories = categories
        db.session.commit()
        flash("Post <%s> updated." % post.title, "success")
        return redirect(url_for("blog.show_post", post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.private.data = post.private
    form.categories.data = [category.id for category in post.categories]
    return render_template("admin/edit_post.html", form=form)


@admin_bp.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash("Post <%s> deleted." % post.title, "success")
    return redirect_back()


@admin_bp.route("/category/new", methods=["GET", "POST"])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        # 可以对name再做一个防重复验证
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash("Category created.", "success")
        return redirect(url_for(".manage_category"))

    return render_template("admin/new_category.html", form=form)


@admin_bp.route("/category/<int:category_id>/edit", methods=["GET", "POST"])
@login_required
def edit_category(category_id):
    if category_id == 1:
        flash("You can not edit the default category.", "warning")
        return redirect(url_for("blog.index"))
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    form.name.data = category.name
    if form.validate_on_submit():
        # 可以对name再做一个防重复验证
        category.name = form.name.data
        db.session.commit()
        flash("Category updated.", "success")
        return redirect(url_for(".manage_category"))

    return render_template("admin/edit_category.html", form=form)


@admin_bp.route("/category/<int:category_id>/delete", methods=["POST"])
@login_required
def delete_category(category_id):
    if category_id == 1:
        flash("You can not delete the default category.", "warning")
        return redirect(url_for("blog.index"))
    category = Category.query.get_or_404(category_id)
    category.delete()
    flash("Category deleted.", "success")
    return redirect(url_for(".manage_category"))


@admin_bp.route("/category/manage", methods=["GET", "POST"])
@login_required
def manage_category():
    categories = Category.query.all()
    return render_template("admin/manage_category.html", categories=categories)


@admin_bp.route("/link/new", methods=["GET", "POST"])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        link = Link(name=form.name.data, url=form.url.data)
        db.session.add(link)
        db.session.commit()
        flash("Link created.", "success")
        return redirect(url_for(".manage_link"))
    return render_template("admin/new_link.html", form=form)


@admin_bp.route("/link/manage", methods=["GET", "POST"])
@login_required
def manage_link():
    links = Link.query.all()
    return render_template("admin/manage_link.html", links=links)


@admin_bp.route("/set-comment/<int:post_id>", methods=["POST"])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    post.can_comment = not post.can_comment
    flash("Comment %s" % ("Enabled" if post.can_comment else "Disabled"))
    db.session.commit()
    return redirect_back()


@admin_bp.route("/comment/manage", methods=["GET"])
@login_required
def manage_comment():
    filter_rule = request.args.get("filter", "all")

    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["BLOG_COMMENT_PER_PAGE"]
    if filter_rule == "unread":
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == "admin":
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query

    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=per_page
    )
    comments = pagination.items
    return render_template(
        "admin/manage_comment.html", comments=comments, pagination=pagination
    )


@admin_bp.route("/comment/<int:comment_id>/approve", methods=["POST"])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash("Comment published.", "success")
    return redirect_back()


@admin_bp.route("/comment/<int:comment_id>/delete", methods=["POST"])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash("Comment deleted.", "success")
    return redirect_back()


@admin_bp.route("/timemachine", methods=["GET", "POST"])
@login_required
@csrf.exempt
def timemachine():
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    if request.method == "POST":
        for post_id, post_time in request.form.items():
            if post_time:
                utc_time = datetime.strptime(post_time, "%Y-%m-%dT%H:%M") - timedelta(
                    hours=8
                )
                post = Post.query.get_or_404(int(post_id))
                post.timestamp = utc_time
                db.session.commit()
    return render_template("admin/timemachine.html", posts=posts)

myblog/blueprints/auth.py
from flask import Blueprint, url_for, redirect, flash, render_template
from myblog.models import Admin
from myblog.forms import LoginForm
from myblog.utils import redirect_back
from flask_login import current_user, login_user, logout_user, login_required

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You have logged in.", "info")
        return redirect(url_for("blog.index"))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash("Welcome back.", "info")
                return redirect_back()
            flash("Invalid username or password.", "warning")
        else:
            flash("No account.", "warning")
    return render_template("auth/login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logout success.", "info")
    return redirect_back()

myblog/templates/base.html
{% from "macros.html" import nav_link %}
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="referrer" content="no-referrer">
        <title>{% block title %}
        {% endblock %} - {{ admin.blog_title|default('MyBlog') }}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme','lux')) }}"
              type="text/css">
        {#<link rel="stylesheet"
              href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
              type="text/css">#}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="/">{{ admin.name|default('MyBlog') }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    {{ render_nav_item('blog.index','Home') }}
                    {{ render_nav_item('blog.about','About') }}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                New <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">Link</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Manage <span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">new</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">
                                    Comment
                                    {% if unread_comments %}
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">Link</a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings', 'Settings') }}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock nav %}

<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}

    {% block content %}
    {% endblock %}
    {% block footer %}
        <footer>
            <p class="float-right">
                <small>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                    {% endif %}
                </small>
            </p>
        </footer>
    {% endblock %}
</main>
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock %}
</body>
</html>

myblog/templates/macros.html
{% macro nav_link(endpoint, text) -%}
    <li class="nav-item {% if request.endpoint and request.endpoint == endpoint %} active{% endif %}">
        <a class="nav-link" href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
    </li>
{%- endmacro %}

{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item {% if not pagination.has_prev %}disabled
        {% endif %}">
            <a class="page-link"
               href="{{ url_for(request.endpoint,page=pagination.prev_num,**kwargs) + fragment if pagination.has_prev else '#' }}">
                <span aria-hidden="true">&larr;</span>Newer
            </a>
        </li>
        <li class="page-item {% if not pagination.has_next %}disabled
        {% endif %}">
            <a class="page-link"
               href="{{ url_for(request.endpoint,page=pagination.next_num,**kwargs) + fragment if pagination.has_next else '#' }}">
                Older <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>
{% endmacro %}